/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tp.nasvirtuel.vues;

import com.tp.nasvirtuel.users.Chercheur;
import com.tp.nasvirtuel.users.Etudiant;
import com.tp.nasvirtuel.users.Membre;
import com.tp.nasvirtuel.users.Personnel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author yirou
 */
public class InscriptionView extends javax.swing.JPanel {
    private final UdsView udsView;

    /**
     * Creates new form InscriptionView
     * @param udsView
     */
    public InscriptionView(UdsView udsView) {
        initComponents();
        this.udsView = udsView;
        
        setColor();
    }

     private void setColor() {
       this.setBackground(UdsView.color_blue);
       jLabel1.setForeground(Color.WHITE);
       jLabel2.setForeground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("Choix Catégorie");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Etudiant", "Chercheur", "Personnel" }));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Pseudo");

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, 0, 320, Short.MAX_VALUE)
                    .addComponent(pseudo))
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String type = jComboBox1.getSelectedItem().toString();
        String pseudoSaisi = pseudo.getText().toLowerCase();
        if (("").equalsIgnoreCase(pseudoSaisi)) {
            JOptionPane.showMessageDialog(null, "Le pseudo ne peut être null");
        } else {
            Membre membre=null;
            switch (type) {
                case "Etudiant":
                    membre = new Etudiant(pseudoSaisi,udsView.getEtudiantGroupe());
                    udsView.getEtudiantGroupe().getListeDesMembres().add(membre);
                    break;
                case "Chercheur":
                    membre = new Chercheur(pseudoSaisi,udsView.getChercheurGroupe());
                    udsView.getChercheurGroupe().getListeDesMembres().add(membre);
                    break;
                case "Personnel":
                    membre = new Personnel(pseudoSaisi,udsView.getPersonnelGroupe());
                    udsView.getPersonnelGroupe().getListeDesMembres().add(membre);
                    break;
            }
            udsView.getUniversite().getListeDesMembres().add(membre);
            udsView.setMembreActif(membre);
            NasManagerView.getInstance().setMembreActif(membre);
            NasManagerView.getInstance().setUdsView(udsView);
            udsView.dispose();
            NasManagerView.getInstance().afficherListeDesGroupes();
            NasManagerView.getInstance().setVisible(true);
            
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pseudo;
    // End of variables declaration//GEN-END:variables

   
}
