/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tp.nasvirtuel.vues;

import com.tp.nasvirtuel.Groupe;
import com.tp.nasvirtuel.objets.Document;
import com.tp.nasvirtuel.objets.Objet;
import com.tp.nasvirtuel.objets.Repertoire;
import com.tp.nasvirtuel.users.Membre;
import com.tp.nasvirtuel.vues.listener.ListeGroupeViewListener;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author yirou
 */
public class NasManagerView extends javax.swing.JFrame {

    private String[] tableHeader = {"Nom objet"};
    private UdsView udsView;
    private static NasManagerView nasManagerView = new NasManagerView(null, null);
    private Membre membreActif;

    /**
     * Creates new form NasManagerView
     *
     * @param udsView
     */
    private NasManagerView(UdsView udsView, Membre membreActif) {
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);
        btn_addGroupe.setIcon(new ImageIcon("src/main/resources/drawable-mdpi/add.png"));
        btn_addUserToGroupe.setIcon(new ImageIcon("src/main/resources/drawable-mdpi/add_user.png"));
        btn_addObject.setIcon(new ImageIcon("src/main/resources/drawable-mdpi/objet.png"));
        back_label.setIcon(new ImageIcon("src/main/resources/drawable-mdpi/back.png"));
        btn_logOut.setIcon(new ImageIcon("src/main/resources/drawable-mdpi/out.png"));
        this.udsView = udsView;
        this.membreActif = membreActif;
        this.groupeListView.addListSelectionListener(new ListeGroupeViewListener());
        this.panelObjetContent.setLayout(new GridLayout(15, 10, 5, 5));
        setColor();

    }

    public Membre getMembreActif() {
        return membreActif;
    }

    public JList getGroupeListView() {
        return groupeListView;
    }

    public void afficherObjetsDuGroupe(Groupe groupe) {
        JButton component;
        for (Objet objet : groupe.getListeObjets()) {
            String classe = objet.getClass().getSimpleName();
            System.out.println(objet.getNom());
            switch (classe) {
                case "Document":
                    component = new JButton();
                    component.setIcon(Document.image);
                    break;
                case "Repertoire":
                    component = new JButton();
                    component.setIcon(Repertoire.image);
                    break;
                default:
                    component = new JButton();
                    component.setIcon(Objet.image);
                    break;
            }
            panelObjetContent.add(component);
        }

    }

    public void afficherListeDesGroupes() {
        Vector<String> groupes = new Vector<>();
        for (Groupe groupe : membreActif.getGroupesCrees()) {
            groupes.add(groupe.getNom());
        }
        groupes.add(membreActif.getGroupeParDefaut().getNom());
        groupeListView.setListData(groupes);
    }

    public void setMembreActif(Membre membreActif) {
        this.membreActif = membreActif;
    }

    public static NasManagerView getInstance() {
        return nasManagerView;
    }

    public void setUdsView(UdsView udsView) {
        this.udsView = udsView;
    }

    public UdsView getUdsView() {
        return udsView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupeListView = new javax.swing.JList();
        panelObjetContent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableContentObjet = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_addGroupe = new javax.swing.JButton();
        btn_addUserToGroupe = new javax.swing.JButton();
        btn_addObject = new javax.swing.JButton();
        back_label = new javax.swing.JLabel();
        btn_logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        groupeListView.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(groupeListView);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        panelObjetContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableContentObjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableContentObjet);

        javax.swing.GroupLayout panelObjetContentLayout = new javax.swing.GroupLayout(panelObjetContent);
        panelObjetContent.setLayout(panelObjetContentLayout);
        panelObjetContentLayout.setHorizontalGroup(
            panelObjetContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        panelObjetContentLayout.setVerticalGroup(
            panelObjetContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjetContentLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_addGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addGroupeActionPerformed(evt);
            }
        });

        btn_addUserToGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUserToGroupeActionPerformed(evt);
            }
        });

        btn_addObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addObjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_addGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addUserToGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addObject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_addGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_addUserToGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_addObject, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable-mdpi/back.png"))); // NOI18N
        back_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelObjetContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelObjetContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addGroupeActionPerformed
        String groupe = JOptionPane.showInputDialog("Nom du groupe");
        if (("").equalsIgnoreCase(groupe)) {
            JOptionPane.showMessageDialog(null, "Le nom est vide");
        } else {
            Groupe groupe1 = membreActif.creerGroupe(udsView.getUniversite().getListeGroupeDisponible().size() + 1, groupe, membreActif, 0);
            udsView.getUniversite().misAjourGroupes(groupe1);
            afficherListeDesGroupes();
        }
    }//GEN-LAST:event_btn_addGroupeActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        this.setVisible(false);
        udsView.setVisible(true);
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void btn_addObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addObjectActionPerformed
        if (groupeListView.getSelectedValue() != null) {
            new AddObject().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez choisir un groupe svp!");
        }

    }//GEN-LAST:event_btn_addObjectActionPerformed

    private void btn_addUserToGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUserToGroupeActionPerformed
        String nom = JOptionPane.showInputDialog(null, "Pseudo du membre");
        Membre membre = udsView.getUniversite().verifierSiMembreExiste(nom);
        if (membre != null) {
            Groupe groupe = udsView.getUniversite().chercherGroupe(groupeListView.getSelectedValue().toString());
            groupe.getListeDesMembres().add(membre);
        } else {
            JOptionPane.showMessageDialog(null, "Ce membre n'existe pas");
        }
    }//GEN-LAST:event_btn_addUserToGroupeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NasManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NasManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NasManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NasManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NasManagerView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_label;
    private javax.swing.JButton btn_addGroupe;
    private javax.swing.JButton btn_addObject;
    private javax.swing.JButton btn_addUserToGroupe;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JList groupeListView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelObjetContent;
    private javax.swing.JTable tableContentObjet;
    // End of variables declaration//GEN-END:variables

    private void setColor() {
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        panelObjetContent.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        btn_addGroupe.setBackground(UdsView.color_blue);
        btn_addObject.setBackground(UdsView.color_blue);
        btn_addUserToGroupe.setBackground(UdsView.color_blue);
        back_label.setBackground(UdsView.color_blue);

    }

}
