/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tp.nasvirtuel.vues;

import com.tp.nasvirtuel.Groupe;
import com.tp.nasvirtuel.Universite;
import com.tp.nasvirtuel.users.Membre;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author yirou
 */
public class UdsView extends javax.swing.JFrame {

    PanelDemarrage panelDemarrage;
    CenterView centerView;
    BotomView botomView;
    TopView topView;
    Universite universite;
    Groupe etudiantGroupe;
    Groupe personnelGroupe;
    Groupe chercheurGroupe;
    Membre membreActif;
    public static Color color_blue = new Color(0x00AFF0);
    public static Color color_blue_foncee = new Color(0x0C7DAF);
    public static Color color_blue_ciel=new Color(0x0095CC);

    /**
     * Creates new form UdsView
     */
    public UdsView() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        BorderLayout layout = new BorderLayout(5, 5);
        setLayout(new BorderLayout());
        panelDemarrage = new PanelDemarrage(this);
        centerView = new CenterView();
        botomView = new BotomView(this);
        topView = new TopView(this);
        universite = new Universite("Univ Savoie Mont Blanc");
        genererGroupe();
        add(topView, BorderLayout.NORTH);
        add(botomView, BorderLayout.SOUTH);
        centerView.getPanelPrincipal().addTab(null, panelDemarrage);
        add(centerView, BorderLayout.CENTER);
//        add(new JButton("Est"), BorderLayout.EAST);
//        add(new JButton("Ouest"), BorderLayout.WEST);
        centerView.setBackground(Color.WHITE);

    }

    public Membre getMembreActif() {
        return membreActif;
    }

    public void setMembreActif(Membre membreActif) {
        this.membreActif = membreActif;
    }

    
    public Universite getUniversite() {
        return universite;
    }

    public PanelDemarrage getPanelDemarrage() {
        return panelDemarrage;
    }

    public Groupe getEtudiantGroupe() {
        return etudiantGroupe;
    }

    public void setEtudiantGroupe(Groupe etudiantGroupe) {
        this.etudiantGroupe = etudiantGroupe;
    }

    public Groupe getPersonnelGroupe() {
        return personnelGroupe;
    }

    public void setPersonnelGroupe(Groupe personnelGroupe) {
        this.personnelGroupe = personnelGroupe;
    }

    public Groupe getChercheurGroupe() {
        return chercheurGroupe;
    }

    public void setChercheurGroupe(Groupe chercheurGroupe) {
        this.chercheurGroupe = chercheurGroupe;
    }

    public CenterView getCenterView() {
        return centerView;
    }

    public BotomView getBotomView() {
        return botomView;
    }

    public TopView getTopView() {
        return topView;
    }

    private void genererGroupe() {
        Membre admin = new Membre("Admin", null);
        etudiantGroupe = new Groupe(universite.getListeGroupeDisponible().size() + 1, "Groupe Etudiant", admin, 0);
        universite.getListeGroupeDisponible().add(etudiantGroupe);
        chercheurGroupe = new Groupe(universite.getListeGroupeDisponible().size() + 1, "Groupe Chercheur", admin, 0);
        universite.getListeGroupeDisponible().add(chercheurGroupe);
        personnelGroupe = new Groupe(universite.getListeGroupeDisponible().size() + 1, "Groupe Personnel", admin, 0);
        universite.getListeGroupeDisponible().add(personnelGroupe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UdsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UdsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UdsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UdsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UdsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
